/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.soltelec.eventos.igrafica;

import com.soltelec.eventos.dao.EventoCdaJpaController;
import com.soltelec.eventos.model.EstadosEvento;
import com.soltelec.eventos.model.EventoCda;
import com.soltelec.eventos.utils.CMensajes;
import java.awt.Font;
import org.apache.log4j.Logger;
//----------

/**
 *
 * @author SOLTELEC
 */
public class Evento_Datos extends javax.swing.JFrame {

    /**
     * Creates new form Evento_Datos
     */
    private String usuario="user";
    
    public Evento_Datos(String usuario) {
       
        initComponents();
        this.usuario=usuario;
        
        TextPrompt pDescripcion = new TextPrompt("Titulo del Evento", this.txtDescripcion);    
        TextPrompt pAccion = new TextPrompt("Accion Ejecutada", this.txtAccion);
        //TextPrompt pPista = new TextPrompt("1:Moto 2:Liviano 3:Mixta", this.txtPista);
        pDescripcion.changeAlpha(0.75f);
        pDescripcion.changeStyle(Font.ITALIC);
    
        pAccion.changeAlpha(0.75f);
        pAccion.changeStyle(Font.ITALIC);
    
        //pPista.changeAlpha(0.75f);
        //pPista.changeStyle(Font.ITALIC);       
        
          this.setResizable(false); ///---
          this.setAutoRequestFocus(true);        
          this.setLocationRelativeTo(null);
          this.setAlwaysOnTop(true);
          this.setDefaultCloseOperation(javax.swing.JFrame.DO_NOTHING_ON_CLOSE);
          this.setVisible(true);
           //Logger.getLogger("igrafica").info("Se inicia un evento manual-");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        dteFInicial = new org.jdesktop.swingx.JXDatePicker();
        dteFFinal = new org.jdesktop.swingx.JXDatePicker();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        txtAccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbPista = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("Fecha de Inicio");

        jLabel2.setText("Fecha de Finalización");

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Iniciado", "Finalizado" }));

        jLabel3.setText("Estado");

        jLabel4.setText("Pista");

        jLabel5.setText("Descripción");

        jLabel6.setText("Acción");

        cmbPista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "1:Moto", "2:Liviano", "3: Mixto" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dteFInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(txtAccion)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dteFFinal, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(cmbPista, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dteFInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dteFFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
              
        Logger.getLogger("igrafica").info("---------------------------------------------------------------------------------------");
        Logger.getLogger("igrafica").info("El usuario "+ usuario +" ha cancelado la inserccion de un EVENTO");
        Logger.getLogger("igrafica").info("----------------------------------------------------------------------------------------");
        
        this.limpiarCampos();
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        EventoCdaJpaController eventoCdaJpaController = new EventoCdaJpaController();
        EventoCda eventoCda = new EventoCda();
        //--------------
        try {                   
              
                if(!txtDescripcion.getText().equals("")
                        &&!txtAccion.getText().equals("")
                            &&cmbEstado.getSelectedIndex()!=0 
                                && cmbPista.getSelectedIndex()!=0
                                    && dteFInicial.getDate()!=null 
                                        && dteFFinal.getDate()!=null ){
                         
                    eventoCda.setDescripcion(txtDescripcion.getText());
                    eventoCda.setAccion(txtAccion.getText());
                    eventoCda.setIdEstado(new EstadosEvento(cmbEstado.getSelectedIndex()));
                    //eventoCda.setPista(txtPista.getText());
                    eventoCda.setPista(String.valueOf(cmbEstado.getSelectedIndex()));
                    eventoCda.setUsuario(usuario);
                    eventoCda.setFinicial(dteFInicial.getDate());
                    eventoCda.setFfinal(dteFInicial.getDate());
                    eventoCdaJpaController.create(eventoCda);///---                  
                
                    System.out.println("-------------------------------------------");
                    System.out.println("--------Evento guardado con Exito.---------");
                    System.out.println("-------------------------------------------");
                    
                    Logger.getLogger("igrafica").info("-----------------------------------------------");
                    Logger.getLogger("igrafica").info("Evento Manual");
                    Logger.getLogger("igrafica").info("Descripcion: "+txtDescripcion.getText() );
                    Logger.getLogger("igrafica").info("Accion: "+txtAccion.getText() );
                     
                    if(String.valueOf(cmbEstado.getSelectedIndex()).equals("1")){
                                Logger.getLogger("igrafica").info("Estado: INICIADO");
                    }else{
                                Logger.getLogger("igrafica").info("Estado: FINALIZADO");
                    }
                    Logger.getLogger("igrafica").info("Fecha inicial: "+dteFInicial.getDate());
                    Logger.getLogger("igrafica").info("Fecha final: "+dteFInicial.getDate());
                    Logger.getLogger("igrafica").info("El usuario  "+usuario+" ha guardado un EVENTO");
                    Logger.getLogger("igrafica").info("-----------------------------------------------");
                    
                    limpiarCampos();
                    this.dispose();          
                }else{
                    Logger.getLogger("igrafica").info("-----------------------------------------------");
                    Logger.getLogger("igrafica").info("--------No se puede guardar el evento----------");
                    Logger.getLogger("igrafica").info("-----------------------------------------------");
                }        
                //--------------
           
        } catch (Exception e) {
                System.out.println("-------------------------------------------------------------------------------");
                System.out.println("No se puede guardar el evento : "+e.getMessage());
                System.out.println("-------------------------------------------------------------------------------");
                limpiarCampos();
        }
      System.exit(0);
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Evento_Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Evento_Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Evento_Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Evento_Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
               // Evento_Datos eventoDatos = new Evento_Datos("users");               
               // eventoDatos.setVisible(true);
                
            }
        });
    }
    
    private void limpiarCampos() {
        txtAccion.setText("");
        txtDescripcion.setText("");
        //txtPista.setText("");
        dteFFinal.setDate(null);
        dteFInicial.setDate(null);
        cmbEstado.setSelectedIndex(0);
        //this.setVisible(false); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbPista;
    private org.jdesktop.swingx.JXDatePicker dteFFinal;
    private org.jdesktop.swingx.JXDatePicker dteFInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtAccion;
    private javax.swing.JTextField txtDescripcion;
    // End of variables declaration//GEN-END:variables

}
